name: Push KubeArmor Relay Image to Docker

on:
  push:
    branches: [main, v*]
  
  create:
    branches:
      - "v*"
      
jobs:
  push-docker-img:
    name: Create and push docker image
    if: github.repository == 'kubearmor/kubearmor-relay-server'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}
      - name: Push images to Docker
        run: |
          if [ ${{ github.ref }} == "refs/heads/main" ]; then
            TAG=latest
          else
            TAG=${GITHUB_REF#refs/*/}
          fi
          ./relay-server/build/push_img.sh $TAG
