name: Push KubeArmor Relay Image to Docker

on:
  push:
    branches: [main]

jobs:
  push-docker-img:
    name: Create auto-policy-discovery img
    if: github.repository == 'kubearmor/kubearmor-relay-server'
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate artifacts
        run: ./relay-server/build/build_img.sh
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}
      - name: Push images to Docker
        run: ./relay-server/build/push_img.sh
